# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
	:disks => {
		:sata1 => {
			:dfile => './sata1.vdi',
			:size => 250,
			:port => 1
		},
		:sata2 => {
            :dfile => './sata2.vdi',
            :size => 250, # Megabytes
			:port => 2
		},
        :sata3 => {
            :dfile => './sata3.vdi',
            :size => 250,
            :port => 3
        },
        :sata4 => {
            :dfile => './sata4.vdi',
            :size => 250, # Megabytes
            :port => 4
        }

	}


  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "1024"]
		  vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]

		  boxconfig[:disks].each do |dname, dconf|
			  unless File.exist?(dconf[:dfile])
				vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
			  end
			  vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]

		  end
          end
 	  box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
yum install -y mdadm
mdadm --create /dev/md0 --metadata=0.90 --level=1 --raid-devices=2 /dev/sd{b,c}
mdadm --create /dev/md1 --metadata=0.90 --level=1 --raid-devices=2 /dev/sd{d,e}
mdadm --create /dev/md2 --metadata=0.90 --level=0 --raid-devices=2 /dev/md{0,1}
fdisk /dev/md2 << EOF
g
n


+100M
n


+100M
n


+100M
n


+100M
n



w
EOF
mkfs.ext3 /dev/md2p1
mkfs.ext3 /dev/md2p2
mkfs.ext3 /dev/md2p3
mkfs.ext3 /dev/md2p4
mkfs.ext3 /dev/md2p5
mkdir /mnt/disk1
mkdir /mnt/disk2
mkdir /mnt/disk3
mkdir /mnt/disk4
mkdir /mnt/disk5
mount /dev/md2p1 /mnt/disk1
mount /dev/md2p2 /mnt/disk2
mount /dev/md2p3 /mnt/disk3
mount /dev/md2p4 /mnt/disk4
mount /dev/md2p5 /mnt/disk5
mkdir /mnt/disk1/test
mkdir /mnt/disk2/test
mkdir /mnt/disk3/test
mkdir /mnt/disk4/test
mkdir /mnt/disk5/test
mkdir /etc/mdadm
echo "DEVICE partitions" > /etc/mdadm/mdadm.conf
mdadm --detail --scan | awk {print} >> /etc/mdadm/mdadm.conf
echo "/dev/md2p1\t/mnt/disk1\text3\tdefaults\t1 2" >> /etc/fstab
echo "/dev/md2p2\t/mnt/disk2\text3\tdefaults\t1 2" >> /etc/fstab
echo "/dev/md2p3\t/mnt/disk3\text3\tdefaults\t1 2" >> /etc/fstab
echo "/dev/md2p4\t/mnt/disk4\text3\tdefaults\t1 2" >> /etc/fstab
echo "/dev/md2p5\t/mnt/disk5\text3\tdefaults\t1 2" >> /etc/fstab

  	  SHELL

      end
  end
end
